# Site settings
baseurl = "http://paulopinto.xyz"
languageCode = "en-us"
title = "Guimar達es iPhonegraph Project"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "Guimar達es iPhonegraph Project"
    subtitle = "A glimpse of a UNESCO Cultural Heritage City by Paulo Pinto"
    author = "Pavel Kanyshev"
    description = "Guimar達es iPhonegraph Project."
    keywords = "Guimar達es, Portugal, photography, portfolio, iphonegraph"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Download"

    # Footer text
    footertext = "Paulo Pinto - 2020"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
